name: Build

on:
 push:
  
 workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm run test
      
    - name: Build Android APK
      run: expo build:android -t apk
      
    - name: Build iOS IPA
      run: expo build:ios -t ipa


   
  

   
